### ISSUE TITLE
automate homebrew release

### ISSUE THREAD

**Issue by chenrui333** [rustq/3body-lang#26]
With either [bump-homebrew-formula-action](https://github.com/mislav/bump-homebrew-formula-action) or [action-homebrew-bump-formula](https://github.com/dawidd6/action-homebrew-bump-formula) into the release pipeline, the project can automate the homebrew releases. Thanks!

But before that, you need to update the repo settings
<img width="774" alt="image" src="https://github.com/rustq/3body-lang/assets/1580956/5beb2abd-f321-4080-a9d4-88fea2a1cb8d">

**Comment by meloalright** [comment]
🤔

**Comment by meloalright** [comment]
Thanks, automate Homebrew release pipeline is great!
