### ISSUE TITLE
输入消息回车无响应

### ISSUE THREAD

**Issue by XuXuClassMate** [rustq/3body-lang#35]
<img width="178" alt="image" src="https://github.com/rustq/3body-lang/assets/76080484/e3e1386a-55d3-4f09-a1ef-90783cd8aacd">

**Comment by meloalright** [comment]
<img width="519" alt="截屏2023-11-01 00 53 06" src="https://github.com/rustq/3body-lang/assets/11075892/ae7409bb-c4e9-4c88-9d9a-df7c61a586bf">
@XuXuClassMate 应该是符合预期 🤣

**Comment by meloalright** [comment]
最后一个表达式会自动帮助打印

**Comment by meloalright** [comment]
🚀
